#!/usr/bin/env bash

# Function to display usage message
usage() {
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
}

# Check if correct number of arguments provided
if [ "$#" -lt 4 ]; then
	usage
fi

# Assigning arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "ssh_key" "$file_path" "$username@$server_ip":~/ || { echo "Failed to trasnfer file."; exit 1; }

echo "File transferred successfully to $username@$server_ip:~/"
