#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

HEADER_VALUE=$(hostname)

sudo bash -c "cat > /etc/nginx/conf.d/custom_header.conf" <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	location / {
		add_header X-Served-By $HEADER_VALUE;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
	}
}
EOF
