#!/usr/bin/env bash
# This script creates a PID file, displays messages, and handles signals

handle_sigterm() {
	echo "I hate the kill command"
}

handle_sigint() {
	echo "Y U no love me?!"
}

handle_sigquit() {
	echo "Deleting PID file and terminating"
	rm -f "/var/run/myscript.pid"
	exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
