#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# and handles SIGTERM signal by displaying "I am invincible!!!"

handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
