#!/usr/bin/env bash
# This script reads and displays information about users from the
# /etc/passwd file using a while loop + IFS

while IFS=: read -r username _ uid gid info home shell
do
	group=$(getent froup "$gid" | cut -d: -f1)
	comment=$(echo "$info" | cut -d',' -f1)
	password=$(echo "$info" | cust -d',' -f2)

	echo "The user $username is part of the $group gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
