#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

ipv4_addresses=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')

echo "$ipv4_addresses"
